Sub-command 'info'
hayorov/apsconnect-cli pull request #1
Opened 2017-07-09 02:25 UTC by romeech

Sub-command 'info' was added. It reads host and user from configs of OA Hub and Kubernetes cluster and then prints to standard output. For example:
```
OA Hub:
	OA hostname: 10.31.225.239:8440, user: admin;
cluster:
	cluster-endpoint: https://130.211.72.0, user: admin; 
```

In case of config absence or corruption 'Not initiated' will be printed instead:

```
OA Hub:
	OA hostname: 10.31.225.239:8440, user: admin;
cluster:
	Not initiated
```

2017-07-28 15:50 UTC, romeech commented
Alexander, please, list all remarks you have here so I could fix it as soon as possible.

2017-08-03 10:15 UTC, spukst3r requested changes

2017-08-03 10:15 UTC, spukst3r commented on apsconnectcli/apsconnect.py
> +    hub_cfg = json.load(open(CFG_FILE_PATH))
Use context manager for reading files:

```python
with open(CFG_FILE_PATH):
    # ...
```

2017-08-03 10:15 UTC, spukst3r commented on apsconnectcli/apsconnect.py
> +    state_not_initiated = '\tNot initiated;'
Drop ';' at the end of each line

2017-08-03 10:15 UTC, spukst3r commented on apsconnectcli/apsconnect.py
> +        for (item_name, check_config, get_info) in [oa_hub_check, kube_check]:
Add empty line before `for`

2017-08-03 10:15 UTC, spukst3r commented on apsconnectcli/apsconnect.py
> +        return state_config_corrupted.format('binding attributes are not assigned')
Use double quotes ("") when writing literals that would be output via `print` or similar. This is useful in case of future localisation.

2017-08-03 15:58 UTC, spukst3r requested changes

2017-08-03 15:58 UTC, spukst3r commented on apsconnectcli/apsconnect.py
> +        host = "{}:{}".format(hub_cfg['host'], hub_cfg['port'])
No need to keep these lines in the context. Just leave the `json.load`

2017-08-03 15:58 UTC, spukst3r commented on apsconnectcli/apsconnect.py
> +        if not isinstance(kube_cfg, dict):
No need to keep these lines in the context. Just leave the `json.load`

2017-08-03 15:58 UTC, spukst3r commented on apsconnectcli/apsconnect.py
> +        kube_check = ('Kube cluster:', lambda: os.path.exists(KUBE_FILE_PATH), _get_cluster_info)
These literals must be in double quotes as well

2017-08-08 16:48 UTC, closed without merging